### PR TITLE
Updated BlazorWebAppOidcBff to Aspire 8.0.1

### PR DESCRIPTION
**Pull request by DaCheeseMan**
Upgraded the BlazorWebAppOidcBff project to Aspire Preview 7

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @DaCheeseMan ... BTW, it's best to open an issue first (or with the PR) because I don't have this repo configured to ping me on every PR that's opened. I do get a ping with every issue. I'll ask Halter to review.

**Comment by guardrex** [comment]
I don't see their usual message for ...

> Contributor License Agreement is not agreed yet. 

Options:

* (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

```
@dotnet-policy-service agree
```

* (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

```
@dotnet-policy-service agree company="Microsoft"
```

Contributor License Agreement: https://dotnetfoundation.org/docs/default-source/default-document-library/contribution-license-agreement.pdf?sfvrsn=40626e42_3

**Comment by DaCheeseMan** [comment]
@dotnet-policy-service agree

**Comment by halter73** [comment]
Now that 8.0.1 is out, can we use that?

**Comment by guardrex** [comment]
I'll follow up in the article with any required updates based on these changes. I kind'a doubt that there will be anything, but it's worth tracking for a look 👀.

**Comment by AdamWyzgol** [comment]
I think it's better to have newer preview then older. Best will be to have stable version in this sample but this PR brings us closer to stable.

**Comment by DaCheeseMan** [comment]
I updated the Aspire packages to 8.0.1

**Comment by guardrex** [comment]
Note to self for article updates later ...

https://learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/allow-unsecure-transport?tabs=windows

Do we want an `https` profile? One is shown in Aspire docs at ...

https://learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/allow-unsecure-transport?tabs=windows#how-to-allow-unsecure-transport

***Or,*** I can take care of it on the article side by stating that the profile only has an HTTP profile with insecure transport enabled and to see their doc for more information.

**Comment by guardrex** [comment]
I'm going to go ahead with this and with article updates today, given that we just hit GA. I'll cover the `https` profile aspect in the article.

Thanks for working on this, @DaCheeseMan 🎷 ... ***HUGE*** help given how busy we are around here!

**Pull request merged**
