### PR TITLE
TwoWayExpander - ability to toggle expander from parent component

### PR DESCRIPTION
**Pull request by hakenr**
Related page in the docs: [Avoid overwriting parameters in ASP.NET Core Blazor | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?view=aspnetcore-8.0)

The `BadExpander.razor` effectively demonstrates the problem: the `Expanded` state can be overwritten by a parent component's re-rendering.

The improved `Expander.razor` avoids resetting the state upon a parent component's re-render. However, this approach only allows for changes to the `Expanded` parameter during the "initial state" (`OnInitialized`):
- The parent component cannot toggle the expander by modifying the `Expanded` parameter value.
- In certain scenarios, an already initialized `Expander` component instance might be reused to render completely different content (for example, when used in a master-detail view and the selected item changes, or when used in a loop without the `@key` directive) and maintains its state without a chance for reset.
Indeed, naming the parameter something like `InitialExpanded` could be more accurate. Many users likely struggle with this sample code as they attempt to toggle the expander externally by changing the `Expander` parameter.

To support both internal and external state changes (enabling expander toggling from outside), using two-way binding for the state might be the only viable solution. This involves incorporating the `ExpandedChanged` parameter and `OnParametersSet` instead of `OnInitialized`. Consequently, the parent component must utilize `@bind-Expanded` to maintain state synchronization.
(An alternative could be to introduce `Expand()` and `Collapse()` methods to the `Expander`, but that's probably beyond the scope of what we're aiming to illustrate on the `overwriting-parameters.md` page.)

I believe we should explain the limitations of the `Expander.razor` with `OnInitialized` approach and offer a `TwoWayExpander.razor` alternative with further explanation.

If you want me to work on this, I can contribute by preparing more polished sample code, including support for older .NET versions, and submit a PR to the AspNetCore.Docs repository for further refinement.

cc @guardrex

### CODE REVIEW

**Review by guardrex — CHANGES_REQUESTED** [review]
Very nice update!

* I've been removing the word "example" from the components in the sample apps. I made the suggestions in the file. Could you rename the file without the word "Example" in the filename?
* WRT to the existing `ExpanderExample` component, I'd like to institute some renaming. What if the child becomes `ExpanderChild`, and the `ExpanderExample` becomes `Expander`? Your added component is `ExpanderToggle`.
* By convention, we place fields above properties. I placed suggestions to move `expanded` up.
* I think you're aware that this example is also in the WASM sample. I understand from your remarks that you'll proceed to version this for the prior samples after the changes are ironed out.

**Comment by hakenr** [comment]
I'll tackle this by the end of the week. 🤞

**Comment by hakenr** [comment]
Sorry, got a bit busy with the perf-tuning talk.  I'll try to wrap this up today or tomorrow.

**Comment by guardrex** [comment]
When u reach this, let's consider three alternatives  ...

* Added, better expander.
* Use your new expander as a replacement. I'd like to see it first.
* A completely different example to replace the bad/good expander that would be simpler.

The section isn't really about the expander... it's about not writing directly to component parameters. I don't really want to make it longer or complexer, as the first two approaches are leading  to.

**Comment by guardrex** [comment]
BTW ... You're not required to pay a lot of attention to the use case or data displayed for a given example. Contributors aren't required to match a theme; but as you may have noticed, the theme of many examples is ***space*** generally and ***sci-fi*** specifically, usually movies and TV over books.

While you're producing any examples for the docs, space/sci-fi themes, use cases, and data are welcome. Personally, I'm sick of the tedious todo list, employee, student, greeter, etc. examples 😩 in the world of programming docs. Even if the code demo is a plain use case, example data doesn't need to be (e.g., Star Trek convo in the [SignalR-Blazor tutorial](https://learn.microsoft.com/aspnet/core/blazor/tutorials/signalr-blazor#run-the-app) article).

That's a minor point. I just mention it in case you want to create a ***cool example*** 😎 for something along the way and have a space/sci-fi idea.

We're allowed to use trademarks and copyrighted content as long as we include proper attribution. For example, the *Class libs* article uses [one of my Jeeps](https://learn.microsoft.com/aspnet/core/blazor/components/class-libraries#create-an-rcl-with-static-assets-in-the-wwwroot-folder), and you'll see the proper [trademarks and attributions at the bottom of the article](https://learn.microsoft.com/aspnet/core/blazor/components/class-libraries#trademarks). It's also done with space companies in the [Dynamically-rendered components article](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-8.0).

**Comment by hakenr** [comment]
WIP. I'm currently considering replacing the expander with a simpler component that has a straightforward one-way state which changes internally. For instance, `<RocketLauncher InitialCountdownValue="10" />`, eliminating the need for external state modifications (unless the component instance is reused for a different rocket).

Additionally, I plan to introduce an example featuring clear two-way state synchronization, possibly with a revamped `Expander` that supports two-way binding. This seems like an effective and straightforward use case where controlling the state from both inside and outside could be necessary.

We can add a summary that these approaches cover the basics for everyday development, although more complex setups might be required for developers creating custom components. (With future xref to the new "custom components development" advanced article.)

**Comment by hakenr** [comment]
Perhaps we could just adjust the current `Expander` to a `ShowMore` component and describe the use case as a one-way _Show more_ button (rather than a full on/off toggle) where you can let the component display some more details to an introductory content. Something like this one: https://www.niceverynice.com/components/expanded-faq-questions-with-show-more-button
We could then transition to a full `Expander` with two-way state tracking in the subsequent section.

Which one do you like more? The `ShowMore` or the `RocketLauncher`?

**Comment by guardrex** [comment]
I don't have a preference on that, but I'd like to see the proposed component set (in a comment here is probably best) if a complete shift is made away from the current expanders.

I'm not excited about switching from `ShowMore` to an `Expander`. I prefer a bad/good SxS comparison of directly writing to and not directly writing to a param. If the current examples are switched to a bad/good `RocketLauncher` or `ShowMore` pair that alleviate your (and @macias) concerns about an unrealistic or incomplete scenario for the "good" demo, then that would be sufficient. There's no need for a third component (i.e., "best" expander demo).

It sounds like we're settling on the following options at the moment ...

* Bad/good `RocketLauncher` pair.
* Bad/good `ShowMore` pair.
* Current direction of the PR: Keep the existing bad/good expander pair and add the `ExpanderToggle` explaining the problems with the "better" expander and how the `ExpanderToggle` solves those problems.

Note on how our doc build system works in case the current components are deleted (or names are changed). It's best to delete ***on a follow-up PR here***, not on this PR. What happens is that our build system will try to incorporate components at any time from this repo. If the docs repo is built for any arbitrary article changes (even ones that don't link to this repo), the build will fail if the components aren't found here. Therefore, leave any components that ultimately won't be used by the article here for the time being. I mentioned some current component renames earlier. Rename but leave anything that would be deleted here (e.g., the `ExpanderExample` :point_right: `Expander` rename ... leave the `ExpanderExample` here for the time being). After the article is updated and merged, then a follow-up PR over here can delete unused components without fear of breaking doc builds.

**Comment by hakenr** [comment]
From these alternatives:
> - Bad/good RocketLauncher pair.
> - Bad/good ShowMore pair.
> - Current direction of the PR: Keep the existing bad/good expander pair and add the ExpanderToggle explaining the problems with the "better" expander and how the ExpanderToggle solves those problems.

...the third option works best for me. It's the only one that demonstrates three phases of the component, two possible approaches to handle the state:
1. The bad one.
2. The good one (if we rename the parameter to InitiallyExpanded to convey the one-way + initial-only contract of the parameter).
3. The "better" one, which will allow for two-way state synchronization.

How about this naming: BadExpander, ShowMoreExpander (the good one), and ToggleExpander (the better one)?

**Comment by guardrex** [comment]
Sounds great to me. Leave the old (current) components in place until after the article is updated ... no 💥 that way 😆 over on the docs repo.

**Comment by hakenr** [comment]
Committed the .NET 8-BWA version. Now, I'll propose changes to the AspNetCore.Docs page. If you agree with these changes, I'll replicate the samples across the other versions.

**Review by guardrex — APPROVED** [review]
Best to keep the "deleted" ones as is. The build system sucks these over for any PR, even ones that don't touch the article where these are used.

**Pull request merged**
