### PR TITLE
Use @rendermode InteractiveServer & Antiforgery in BlazorWebAppEFCore

### PR DESCRIPTION
**Pull request by yelizsevinc**
In the .NET 8 version of BlazorWebAppEFCore;
- Enabled support for interactive render modes by using `AddInteractiveServerComponents` and `AddInteractiveServerRenderMode` in Program.cs as the documentation refers: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#enable-support-for-interactive-render-modes
- Used `@rendermode RenderMode.InteractiveServer` directive instead of the legacy `@attribute [RenderModeServer]` as the documentation refers: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-a-component-definition
- Added [`app.UseAntiforgery()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.antiforgeryapplicationbuilderextensions.useantiforgery?view=aspnetcore-8.0) directive in Program.cs

FYI @guardrex

### CODE REVIEW

**Comment by yelizsevinc** [comment]
@dotnet-policy-service agree

**Comment by guardrex** [comment]
Thanks @yelizsevinc ...

Add ...

```razor
@using static Microsoft.AspNetCore.Components.Web.RenderMode
```

... to the `_Imports` file and use `InteractiveServer` (no `RenderMode` class name) for the `@rendermode` directives.

**Comment by yelizsevinc** [comment]
Thank you very much for your review and suggestion @guardrex 😊

**Comment by guardrex** [comment]
Thanks ... I'll merge this on release day.

**Comment by ymsodev** [comment]
it looks like a duplicate of https://github.com/dotnet/blazor-samples/pull/120

**Comment by guardrex** [comment]
The prior PR takes care of the updates.

**Pull request closed without merging**
